const streamingTable = [
    {
      id: 1,
      nome: "Stranger Things",
      qualidade: "4K HDR",
      genero: "Ficção Científica, Drama, Terror",
      classificacao: "16+",
      plataforma: "Netflix",
    },
    {
      id: 2,
      nome: "The Crown",
      qualidade: "Full HD",
      genero: "Drama Histórico",
      classificacao: "12+",
      plataforma: "Netflix",
    },
    {
      id: 3,
      nome: "Lupin",
      qualidade: "4K",
      genero: "Mistério, Ação, Aventura",
      classificacao: "14+",
      plataforma: "Netflix",
    },
    {
      id: 4,
      nome: "O Gambito da Rainha",
      qualidade: "Full HD",
      genero: "Drama",
      classificacao: "14+",
      plataforma: "Netflix",
    },
    {
      id: 5,
      nome: "Wandinha",
      qualidade: "4K HDR",
      genero: "Comédia, Fantasia",
      classificacao: "12+",
      plataforma: "Netflix",
    },
    {
      id: 6,
      nome: "Arcane",
      qualidade: "4K",
      genero: "Animação, Fantasia, Ação",
      classificacao: "14+",
      plataforma: "Netflix",
    },
    {
      id: 7,
      nome: "Dark",
      qualidade: "Full HD",
      genero: "Ficção Científica, Suspense",
      classificacao: "16+",
      plataforma: "Netflix",
    },
    {
      id: 8,
      nome: "The Witcher",
      qualidade: "4K HDR",
      genero: "Fantasia, Aventura",
      classificacao: "16+",
      plataforma: "Netflix",
    },
    {
      id: 9,
      nome: "The Mandalorian",
      qualidade: "4K HDR",
      genero: "Ficção Científica, Aventura",
      classificacao: "12+",
      plataforma: "Disney+",
    },
    {
      id: 10,
      nome: "Loki",
      qualidade: "4K",
      genero: "Ação, Fantasia",
      classificacao: "14+",
      plataforma: "Disney+",
    },
  ];
  
  export default { streamingTable };
 